### ISSUE TITLE
Error when loading weights, I want to train it on another dataset, and the num_classes is not 65

### ISSUE THREAD

**Issue by Nemasery** [salman-h-khan/PL-ZSD_Release#14]
Traceback (most recent call last):
  File "keras_retinanet/bin/train_vocab_w2v.py", line 407, in <module>
    main()
  File "keras_retinanet/bin/train_vocab_w2v.py", line 361, in main
    training_model.load_weights('Model/resnet50_csv_50_focal_seen_w2v.h5')
  File "/usr/local/miniconda3/envs/keras/lib/python3.6/site-packages/keras/engine/network.py", line 1166, in load_weights
    f, self.layers, reshape=reshape)
  File "/usr/local/miniconda3/envs/keras/lib/python3.6/site-packages/keras/engine/saving.py", line 1045, in load_weights_from_hdf5_group
    reshape=reshape)
  File "/usr/local/miniconda3/envs/keras/lib/python3.6/site-packages/keras/engine/saving.py", line 682, in preprocess_weights_for_loading
    weights = convert_nested_model(weights)
  File "/usr/local/miniconda3/envs/keras/lib/python3.6/site-packages/keras/engine/saving.py", line 658, in convert_nested_model
    original_backend=original_backend))
  File "/usr/local/miniconda3/envs/keras/lib/python3.6/site-packages/keras/engine/saving.py", line 801, in preprocess_weights_for_loading
    weights[0] = np.transpose(weights[0], (3, 2, 0, 1))
  File "/usr/local/miniconda3/envs/keras/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 598, in transpose
    return _wrapfunc(a, 'transpose', axes)
  File "/usr/local/miniconda3/envs/keras/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 51, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: axes don't match array

**Comment by shafin5** [comment]
Form the error; I guess you are trying to use Model/resnet50_csv_50_focal_seen_w2v.h5 weights to initialize the network in keras_retinanet/bin/train_vocab_w2v.py. Please note that resnet50_csv_50_focal_seen_w2v.h5 is not a pre-trained weights of train_vocab_w2v.py. Their architectures are different. train_vocab_w2v.py uses vocabulary and metric learning concept whereas resnet50_csv_50_focal_seen_w2v.h5 only use seen word vectors without considering any vocabulary metric. However, both architectures have many common layers. Therefore, you can consider resnet50_csv_50_focal_seen_w2v.h5 to partially initialize the common layers of train_vocab_w2v.py.
